#! /bin/sh
### BEGIN INIT INFO
# Provides:          ondemand
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Set the CPU Frequency Scaling governor to "ondemand"
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

AVAILABLE="/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors"

case "$1" in
    start)
    	start-stop-daemon --start --background --exec /etc/init.d/ondemand -- background
        ;;
    background)
	sleep 60 # probably enough time for desktop login

	[ -f $AVAILABLE ] || exit 0
	read governors < $AVAILABLE
	case $governors in
		*interactive*)
			GOVERNOR="interactive"
			break
			;;
		*ondemand*)
			GOVERNOR="ondemand"
			break
			;;
		*)
			exit 0
			;;
	esac

	for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
	do
		[ -f $CPUFREQ ] || continue
		echo -n $GOVERNOR > $CPUFREQ
	done

	# set some defaults
	case $GOVERNOR in
		*interactive*)
			if [ -d /sys/module/cpu_tegra3 ]; then
				echo 0 >/sys/module/cpu_tegra3/parameters/no_lp
				echo 1 >/sys/module/cpu_tegra3/parameters/auto_hotplug
			fi
			if [ -d /sys/module/cpuidle ]; then
				echo 0 >/sys/module/cpuidle/parameters/lp2_in_idle
			fi
			echo 2 >/sys/devices/system/cpu/cpufreq/interactive/boost_factor
			echo 1 >/sys/devices/system/cpu/cpufreq/interactive/input_boost
			echo 80 >/sys/devices/system/cpu/cpufreq/interactive/sustain_load
			;;
	esac
	;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
